# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fe5dade38289a1588eb3c98086e38d75075d2dd2514d3f4c18264b8e7638bcde4d174a4f6006fc42ed24c7620aca12551817f82f469b5da6c0d46c1641a9236

test:
  secret_key_base: 2206c1f6618ca79d7d28cf9b6a738c6d1efbc4809e597ad017b6370f1851fe8b6a1cbd953b01e50cbcb1f1069b4b0f7ec5d3648dd7b6a71fea632cfeb8da35b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
